### PR TITLE
queue_linked list

### PR DESCRIPTION
**Pull request by JainVanshika**

### CODE REVIEW

**Comment by Suhel-Kap** [comment]
> 

Hi
Umm, may I ask why are you so agressively committing to a dead repository?
Also are you from SCET or did you stumble upon my repository randomly?

**Comment by jainvanshi3105** [comment]
> > 
> 
> Hi Umm, may I ask why are you so agressively committing to a dead repository? Also are you from SCET or did you stumble upon my repository randomly?

heya...sorry I'm a started on Github, so I didn't know that it was a dead repository

**Comment by Suhel-Kap** [comment]
> > > 
> > 
> > 
> > Hi Umm, may I ask why are you so agressively committing to a dead repository? Also are you from SCET or did you stumble upon my repository randomly?
> 
> heya...sorry I'm a started on Github, so I didn't know that it was a dead repository

yeah no issues, I had made this for Hacktoberfest 2021
also if you'd like to contribute to open source projects, I'd suggest having a look at these sites [first timers only](https://www.firsttimersonly.com/), [first-contributions](https://github.com/firstcontributions/first-contributions), [code triage](https://www.codetriage.com/) and [open-source Friday](https://opensourcefriday.com/).
Hope it helps!

**Comment by jainvanshi3105** [comment]
> > > > 
> > > 
> > > 
> > > Hi Umm, may I ask why are you so agressively committing to a dead repository? Also are you from SCET or did you stumble upon my repository randomly?
> > 
> > 
> > heya...sorry I'm a started on Github, so I didn't know that it was a dead repository
> 
> yeah no issues, I had made this for Hacktoberfest 2021 also if you'd like to contribute to open source projects, I'd suggest having a look at these sites [first timers only](https://www.firsttimersonly.com/), [first-contributions](https://github.com/firstcontributions/first-contributions), [code triage](https://www.codetriage.com/) and [open-source Friday](https://opensourcefriday.com/). Hope it helps!

thank you so much :)

**Pull request closed without merging**
